#开发环境配置

server:
  # 服务端口
  port: 80

spring:
  # 数据源配置，请修改为你项目的实际配置 (测试表  在 resources 目录下)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    username: demo
    password: demo
